### ISSUE TITLE
Revert extra lock on ioprio

### ISSUE THREAD

**Issue by HazouPH** [SpiritCroc/android_kernel_sony_msm8974#1]
This fixes 3AM bug on our devices. see my fork of your repo:
[https://github.com/HazouPH/android_kernel_sony_msm8974/commits/AICP-IOPRIO](https://github.com/HazouPH/android_kernel_sony_msm8974/commits/AICP-IOPRIO)

**Comment by SpiritCroc** [comment]
Thanks for the hint!

I'm currently using the AICP kernel repo (https://github.com/AICP/kernel_sony_msm8974/tree/n7.1), I'll update it later (probably rebase to Lineage one so I can use it for shinano/castor as well, which already contains https://github.com/LineageOS/android_kernel_sony_msm8974/commit/0db133c30c6bc26ac4b7d0b9398bbed23ef2a6f0 )

Feel free to push to the AICP gerrit if you want to improve/fix anything else ;)

**Comment by HazouPH** [comment]
Yup, didn't even know off that one. Could have saved me an extra night.

**Comment by SpiritCroc** [comment]
I know that feel haha
